"""
Default configuration constants for Sentinel.
"""

DEFAULT_TRAINING_SECONDS = 1800

LAMBDA_SHORT = 0.01
LAMBDA_LONG = 0.001
EPSILON_BASE = 1e-4
CONDITION_NUMBER = 1e6

CONTAMINATION_LIMIT = 0.8
RISK_ALERT_THRESHOLD = 20.0
AUDIO_ALARM_THRESHOLD = 25.0

CUSUM_K = 0.05
CUSUM_THRESHOLD = 10.0
